# Generated by Django 4.2.5 on 2023-10-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciondecursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineaasignacion',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='lineaasignacion',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='lineaasignacion',
            name='user',
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
        migrations.DeleteModel(
            name='LineaAsignacion',
        ),
    ]
