# Generated by Django 4.2.5 on 2023-10-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_alter_categoriacurso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacurso',
            options={'verbose_name': 'categoriacurso', 'verbose_name_plural': 'categoriascurso'},
        ),
    ]
