# Generated by Django 4.2.5 on 2023-10-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_alter_categoriacurso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacurso',
            options={'verbose_name': 'CategoriaCurso', 'verbose_name_plural': 'CategoriasCurso'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
