# Generated by Django 4.2.5 on 2023-10-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0004_alter_categoriacurso_options_alter_curso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacurso',
            options={'verbose_name': 'categoriacurso', 'verbose_name_plural': 'categoriascurso'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
    ]
