# Generated by Django 4.2.5 on 2023-10-05 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0006_alter_categoriacurso_options_alter_curso_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
