# Generated by Django 4.2.5 on 2023-10-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0007_curso_created_curso_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaCurso',
            new_name='CategoriaCur',
        ),
        migrations.AlterModelOptions(
            name='categoriacur',
            options={'verbose_name': 'categoriaCurso', 'verbose_name_plural': 'categoriasCurso'},
        ),
    ]
