# Generated by Django 4.2.5 on 2023-10-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conocenos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conocenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='conocenos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'conocenos',
                'verbose_name_plural': 'conocenos',
            },
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
