# Generated by Django 4.2.5 on 2023-10-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conocenos', '0002_conocenos_delete_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conocenos',
            name='contenido',
            field=models.CharField(max_length=1000),
        ),
    ]
