# Generated by Django 4.2.5 on 2023-10-14 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
